# Generated by Django 4.1.7 on 2023-02-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0024_htmlbunchstorage_source_html"),
        ("cars", "0003_alter_car_html_storage_alter_car_url_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.carmodel",
            ),
            preserve_default=False,
        ),
    ]
