# Generated by Django 4.1.7 on 2023-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
