# Generated by Django 4.1.7 on 2023-02-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_car_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="accessories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="additional_options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="co2_emission",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="co2_emission_standard",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="coc",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="damage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="doors",
            field=models.PositiveSmallIntegerField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="drivable",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_size",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="first_registration",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="four_wheel_drive",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="high_value_equipment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="interior_colour",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="model_year",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="number_of_keys",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="number_of_seats",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="origin_country",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="paint",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="pickup_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="power",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="registration_documents",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="selling_office",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="transmission_type",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="vat",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
