# Generated by Django 4.1.7 on 2023-02-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_car_doors_alter_car_number_of_keys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="body_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="co2_emission",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="co2_emission_standard",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="coc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="first_registration",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="four_wheel_drive",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="interior_colour",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="origin_country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="paint",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="power",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="registration_documents",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="selling_office",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="vat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
