# Generated by Django 4.1.7 on 2023-02-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_alter_car_body_type_alter_car_co2_emission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
