# Generated by Django 4.1.7 on 2023-02-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_rename_doors_car_doors_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="number_of_keys",
            new_name="keys_count",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="number_of_seats",
            new_name="seats_count",
        ),
    ]
