# Generated by Django 4.1.7 on 2023-02-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_urlstorage_car_model"),
        ("cars", "0013_car_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="url_storage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="url",
                to="storage.urlstorage",
            ),
        ),
    ]
