# Generated by Django 4.1.7 on 2023-02-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_urlstorage_car_model"),
        ("cars", "0014_alter_car_url_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="html_storage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="html",
                to="storage.htmlstorage",
            ),
        ),
    ]
