# Generated by Django 4.1.7 on 2023-03-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0026_alter_urlstorage_car_model"),
        ("cars", "0015_alter_car_html_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="html_storage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="car",
                to="storage.htmlstorage",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="url_storage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="storage.urlstorage",
            ),
        ),
    ]
