# Generated by Django 4.1.7 on 2023-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0017_alter_car_body_type_alter_car_co2_emission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="transmission_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
