# Generated by Django 4.1.5 on 2023-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_url", models.URLField(max_length=255, unique=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
