# Generated by Django 4.1.5 on 2023-02-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_create_url_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HtmlStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_html", models.TextField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "url_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="html",
                        to="storage.urlstorage",
                    ),
                ),
            ],
        ),
    ]
