# Generated by Django 4.1.5 on 2023-02-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_remove_related_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "providers",
            },
        ),
    ]
