# Generated by Django 4.1.5 on 2023-02-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_create_brands"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlBunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_url", models.URLField(max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="storage.brand"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.provider",
                    ),
                ),
            ],
            options={
                "db_table": "url_bunches",
            },
        ),
    ]
