# Generated by Django 4.1.7 on 2023-02-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_create_url_bunch"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UrlBunch",
            new_name="UrlBunchStorage",
        ),
        migrations.AlterModelTable(
            name="urlbunchstorage",
            table="url_bunche_storage",
        ),
    ]
