# Generated by Django 4.1.7 on 2023-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_rename_urlbunch_urlbunchstorage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "url_types",
            },
        ),
    ]
