# Generated by Django 4.1.7 on 2023-02-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_urltype"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlstorage",
            name="provider",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.provider",
            ),
        ),
        migrations.AddField(
            model_name="htmlstorage",
            name="url_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="storage.urltype",
            ),
        ),
        migrations.AddField(
            model_name="urlstorage",
            name="provider",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.provider",
            ),
        ),
    ]
