# Generated by Django 4.1.7 on 2023-02-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_htmlstorage_provider_htmlstorage_url_type_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="htmlstorage",
            table="html_storage",
        ),
        migrations.AlterModelTable(
            name="urlstorage",
            table="url_storage",
        ),
    ]
