# Generated by Django 4.1.7 on 2023-02-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_htmlstorage_table_alter_urlstorage_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="htmlstorage",
            name="url_type",
        ),
        migrations.DeleteModel(
            name="UrlType",
        ),
    ]
