# Generated by Django 4.1.7 on 2023-02-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_remove_htmlstorage_url_type_delete_urltype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="htmlstorage",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="urlbunchstorage",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="urlstorage",
            name="provider",
        ),
        migrations.DeleteModel(
            name="Provider",
        ),
    ]
