# Generated by Django 4.1.7 on 2023-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_remove_htmlstorage_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlstorage",
            name="type_url",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "single"), (2, "bunch")], default=1
            ),
        ),
    ]
