# Generated by Django 4.1.7 on 2023-02-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_urlstorage_type_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="urlstorage",
            old_name="type_url",
            new_name="type",
        ),
    ]
