# Generated by Django 4.1.7 on 2023-02-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0016_carmodel_remove_urlbunchstorage_brand_delete_brand_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="urlbunchstorage",
            table="url_bunch_storage",
        ),
    ]
