# Generated by Django 4.1.7 on 2023-02-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0017_alter_urlbunchstorage_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="HtmlBunchStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "url_bunch_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.urlbunchstorage",
                    ),
                ),
            ],
            options={
                "db_table": "html_bunch_storage",
            },
        ),
    ]
