# Generated by Django 4.1.7 on 2023-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0018_htmlbunchstorage"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlbunchstorage",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
