# Generated by Django 4.1.7 on 2023-02-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0019_urlbunchstorage_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlbunchstorage",
            name="url_bunch_storage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.urlbunchstorage",
            ),
        ),
        migrations.AlterField(
            model_name="urlbunchstorage",
            name="car_model",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="storage.carmodel"
            ),
        ),
    ]
