# Generated by Django 4.1.7 on 2023-02-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0020_alter_htmlbunchstorage_url_bunch_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urlstorage",
            name="type",
        ),
    ]
