# Generated by Django 4.1.7 on 2023-02-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0022_htmlbunchstorage_source_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="htmlbunchstorage",
            name="source_html",
        ),
    ]
