# Generated by Django 4.1.7 on 2023-02-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0023_remove_htmlbunchstorage_source_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlbunchstorage",
            name="source_html",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
