# Generated by Django 4.1.7 on 2023-03-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_urlstorage_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlstorage",
            name="car_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.carmodel",
            ),
        ),
    ]
