[tool.poetry]
name = "goodauto"
version = "0.1.0"
description = ""
authors = ["Sergey Karpuk <sergeykarpuk@yandex.by>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.5"
python-dotenv = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
