# Generated by Django 4.1.5 on 2023-02-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0003_remove_related_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlFrontier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "url_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.urlstorage",
                    ),
                ),
            ],
        ),
    ]
