# Generated by Django 4.1.5 on 2023-02-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_create_car"),
        ("storage", "0003_remove_related_name"),
        ("sheduler", "0001_create_crawl_frontier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserFrontier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.car"
                    ),
                ),
                (
                    "html_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.htmlstorage",
                    ),
                ),
            ],
        ),
    ]
