# Generated by Django 4.1.7 on 2023-02-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_htmlstorage_table_alter_urlstorage_table"),
        ("sheduler", "0003_alter_crawlfrontier_table_alter_parserfrontier_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrawlFrontier",
            new_name="CrawlerFrontier",
        ),
    ]
