# Generated by Django 4.1.7 on 2023-02-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheduler", "0004_rename_crawlfrontier_crawlerfrontier"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="crawlerfrontier",
            table=None,
        ),
        migrations.AlterModelTable(
            name="parserfrontier",
            table=None,
        ),
    ]
