# Generated by Django 4.1.7 on 2023-02-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheduler", "0006_crawlerfrontier_type_url_parserfrontier_type_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawlerfrontier",
            name="type_url",
        ),
        migrations.RemoveField(
            model_name="parserfrontier",
            name="type_url",
        ),
    ]
