#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False
  become: True

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Create group '{{ group_name }}'
      group:
        name: "{{ group_name }}"
        state: present

    - name: Create user '{{ user_name }}'
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        group: "{{ group_name }}"
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: "{{ user_ssh_private_key_path }}"

    - name: Allow '{ group_name }}' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%{{ group_name }}"
        line: "%{{ group_name }} ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Add SSH authorized_key to {{ user_name }}
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', '{{ public_key_file }}') }}"
