#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Create cron logs dir
      file:
        path: "{{ cron_logs_path }}"
        state: file
        recurse: yes

    - name: Start cron services
      systemd:
        name: cron
        state: started
        daemon_reload: yes
        enabled: yes
      become: True

    - name: Run django cron
      cron:
        name: Record the current time
        job: "date >> {{ cron_logs_path }}; {{ python_path }} {{ site_path }}/manage.py runcrons 2>&1 >> {{ cron_logs_path }}"
