#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: True

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: "Ensure Google linux signing key present"
      become: True
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: "Ensure Google chrome repo present"
      become: True
      apt_repository:
        repo: "deb [arch=x86_64] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: "google-chrome"
        state: present
        update_cache: yes

    - name: "Ensure Google chrome present"
      become: True
      apt:
        name: "google-chrome-stable"
        state: present

    - name: Downloal and unarchive chromedriver
      unarchive:
        src: https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_linux64.zip
        dest: "{{ site_path }}/sheduler"
        include: ["chromedriver"]
        remote_src: yes
      tags: driver
