- hosts: all
  gather_facts: no

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes

    - name: Enable virtual host
      ansible.builtin.file:
        src: /home/chess/www/goodauto.by/config/nginx/goodauto.by
        dest: /etc/nginx/sites-enabled/goodauto.by
        state: link
      become: yes
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: yes
