#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False
  become: True

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Create logs dir
      file:
        path: "{{ nginx_logs_path }}"
        state: directory
        recurse: yes

    - name: Enable virtual host
      file:
        src: "{{ nginx_config_path }}"
        dest: "{{ nginx_site_enabled_link }}"
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
