#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: no

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - htop
        - make
        - tree
        - unzip
        - zip
        # - zsh
        # - supervisor
        - tmux
        - git
        - curl
        - wget
        - gcc
        - build-essential
        - gnumeric
        - python3-venv
        - python3-lxml
        - python3-dev
        - python-is-python3
        - python3-dev
        - python3-libxml2
        - python3-pil
        - python3-virtualenv
        - libxslt1-dev
        - libbz2-dev
        - libcurl4-openssl-dev
        - libffi-dev
        - libfreetype6-dev
        - libjpeg-dev
        - liblzma-dev
        - libncurses5-dev
        - libncursesw5-dev
        - libpq-dev
        - libreadline-dev
        - libsqlite3-dev
        - libssl-dev
        - libxslt-dev
        - libxslt1-dev
        - libxml2-dev
        - llvm
        - tk-dev
        - xz-utils
        - zlib1g-dev
      become: yes
      tags: apt
