#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False

  tasks:
    - name: clone github repository
      ansible.builtin.git:
        repo: git@github.com:zhabinka/goodauto.git
        dest: ~/www/goodauto.by
        clone: True
        update: True
        force: True
      tags: git

    - name: install packages in virtualenv
      ansible.builtin.pip:
        requirements: ~/www/goodauto.by/requirements.txt
        virtualenv: ~/www/goodauto.by/.venv

    - name: create gunicorn socket folder
      ansible.builtin.file:
        path: ~/www/goodauto.by/config/gunicorn
        state: directory

    - name: create log dirs
      file:
        path: ~/www/goodauto.by/logs/{{ item }}
        state: directory
        recurse: yes
      with_items:
        - gunicorn
        - cron

    - name: check gunicorn service file setup
      stat:
        path: /etc/systemd/system/gunicorn.service
      register: link

    - name: setup gunicorn service
      ansible.builtin.shell:
        cmd: ln -s /home/chess/www/goodauto.by/config/systemd/gunicorn.service /etc/systemd/system
      # [TODO]: refusing to convert from directory to symlink for /etc/systemd/system/
      # ansible.builtin.file:
      #   src: /home/chess/www/goodauto.by/config/systemd/gunicorn.service
      #   dest: /etc/systemd/system/
      #   state: link
      when: not link.stat.exists
      become: True
      notify:
        - start gunicorn

    - name: create an entry like 'date >> <logs>'
      cron:
        name: record the current time
        special_time: 'hourly'
        job: date >> /home/chess/www/goodauto.by/logs/cron/current_date

  handlers:
    - name: start sevices gunicorn, cron
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        daemon_reload: True
        enabled: True
      loop:
        - gunicorn
        - cron
      become: True
