- hosts: all
  gather_facts: False

  tasks:
    - name: clone github repository
      ansible.builtin.git:
        repo: git@github.com:zhabinka/goodauto.git
        dest: ~/www/goodauto.by
        clone: True
        update: True
        force: True
      tags: git

    - name: install packages in virtualenv
      ansible.builtin.pip:
        requirements: ~/www/goodauto.by/requirements.txt
        virtualenv: ~/www/goodauto.by/.venv

    - name: setup gunicorn service
      ansible.builtin.shell:
        cmd: ln -s /home/chess/www/goodauto.by/config/systemd/gunicorn.service /etc/systemd/system
      # [TODO]: refusing to convert from directory to symlink for /etc/systemd/system/
      # ansible.builtin.file:
      #   src: /home/chess/www/goodauto.by/config/systemd/gunicorn.service
      #   dest: /etc/systemd/system/
      #   state: link
      become: True
      notify:
        - start gunicorn

  handlers:
    - name: start gunicorn
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
      ansible.builtin.systemd:
        name: gunicorn
        state: started
        daemon_reload: True
        enabled: True
      become: True
