#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Clone github repository
      git:
        repo: git@github.com:zhabinka/goodauto.git
        dest: "{{ site_path }}"
        clone: yes
        update: yes
        force: yes
      tags: git

    - name: Install packages in virtualenv
      pip:
        requirements: "{{ requirements_path }}"
        virtualenv: "{{ virtualenv_path }}"

    - name: Create gunicorn socket folder
      file:
        path: "{{ gunicorn_socket_dir }}"
        state: directory

    - name: Create log dirs
      file:
        path: ~/www/goodauto.by/logs/{{ item }}
        state: directory
        recurse: yes
      with_items:
        - gunicorn
        - cron

    - name: Check gunicorn service file setup
      stat:
        path: "{{ gunicorn_service_config_path }}"
      register: link

    - name: Setup gunicorn service
      shell:
        cmd: "ln -s {{ gunicorn_config }} /etc/systemd/system"
      # [TODO]: refusing to convert from directory to symlink for /etc/systemd/system/
      # ansible.builtin.file:
      #   src: /home/chess/www/goodauto.by/config/systemd/gunicorn.service
      #   dest: /etc/systemd/system/
      #   state: link
      when: not link.stat.exists
      become: True

    - name: Create an entry like 'date >> <logs>'
      cron:
        name: Record the current time
        special_time: 'hourly'
        job: date >> /home/chess/www/goodauto.by/logs/cron/current_date

    - name: Start sevices (gunicorn, cron)
      systemd:
        name: "{{ item }}"
        state: started
        daemon_reload: yes
        enabled: yes
      loop:
        - gunicorn
        - cron
      become: True
