#! /usr/bin/env ansible-playbook

- hosts: all
  gather_facts: False

  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Create virtualenv with requirements
      pip:
        requirements: "{{ requirements_path }}"
        virtualenv: "{{ virtualenv_path }}"
      tags: req

    - name: Create log dirs
      file:
        path: "{{ site_path }}/logs/{{ item }}"
        state: directory
        recurse: yes
      with_items:
        - gunicorn
        - cron

    - name: Check gunicorn service config
      stat:
        path: "{{ gunicorn_service_config_path }}"
      register: gunicorn_service

    - name: Check gunicorn socket config
      stat:
        path: "{{ gunicorn_socket_config_path }}"
      register: gunicorn_socket

    - name: Setup gunicorn service
      shell:
        cmd: "ln -s {{ gunicorn_service_config }} /etc/systemd/system"
      # [TODO]: refusing to convert from directory to symlink for /etc/systemd/system/
      # ansible.builtin.file:
      #   src: /home/chess/www/goodauto.by/config/systemd/gunicorn.service
      #   dest: /etc/systemd/system/
      #   state: link
      when: not gunicorn_service.stat.exists
      become: True

    - name: Setup gunicorn socket
      shell:
        cmd: "ln -s {{ gunicorn_socket_config }} /etc/systemd/system"
      when: not gunicorn_socket.stat.exists
      become: True

    - name: Restart gunicorn services
      systemd:
        name: gunicorn
        state: restarted
        daemon_reload: yes
        enabled: yes
      become: True

    - name: Start cron services
      systemd:
        name: cron
        state: started
        daemon_reload: yes
        enabled: yes
      become: True

    - name: Create an entry like 'date >> <logs>'
      cron:
        name: Record the current time
        special_time: 'hourly'
        job: date >> /home/chess/www/goodauto.by/logs/cron/current_date

    - name: Make django migrate
      community.general.django_manage:
        command: migrate
        project_path: "{{ site_path }}"
        virtualenv: "{{ virtualenv_path }}"
      tags: django
